// pitchdeck/app/components/Landing.vue
<script setup>
import gsap from "gsap";

const title = ref(null);
const subtitle = ref(null);

onMounted(() => {
  gsap.fromTo(title.value, { x: -50 }, { x: 0 });
  gsap.fromTo(subtitle.value, { x: 50 }, { x: 0 });
});
</script>

<template>
  <section
    class="w-full h-[100vh] bg-greentomgreen text-antiprimary text-center flex flex-col justify-center items-center font-bold"
  >
    <h1 ref="title" class="text-6xl text-shadow-black">
      Een rugzak voor de volgende generatie...
    </h1>
    <h2 ref="subtitle" class="text-5xl mt-5 text-shadow-black">
      ...en de generaties daarna
    </h2>
  </section>
</template>

// pitchdeck/src/components/sections/Landing.tsx
import { useGSAP } from "@gsap/react";
import { clsx } from "clsx";
import { gsap } from "gsap";
import { FC, useRef } from "react";
import { ParticlesEffect } from "../ParticlesEffect";
import { Section } from "../Section";

export const Landing: FC = () => {
  const title = useRef(null);
  const subTitle = useRef(null);

  useGSAP(() => {
    gsap.fromTo(title.current, { x: -100 }, { x: 0 });
    gsap.fromTo(subTitle.current, { x: 100 }, { x: 0 });
  });

  return (
    <Section
      className={clsx(
        "bg-gtgreen flex flex-col content-center items-center justify-center",
        "text-antiprimary relative overflow-hidden text-center font-bold",
      )}
    >
      <h1 ref={title} className={clsx("z-10 text-6xl")}>
        Een rugzak voor de volgende generatie...
      </h1>
      <h2 ref={subTitle} className={clsx("z-10 mt-5 text-5xl")}>
        ...en de generaties daarna
      </h2>
      <div className="absolute inset-0">
        <ParticlesEffect />
      </div>
    </Section>
  );
};
